### ISSUE TITLE
All emails are displaying in the groups page(Functional Requirement)

### ISSUE THREAD

**Issue by BhanuMotupalli** [Ajaykumarunt/Best_Team_Ever#27]
![Bug 2](https://github.com/Ajaykumarunt/Best_Team_Ever/assets/126606573/5085e588-3efc-432a-8eb8-bfc922f823cc)
 After clicking on the create button in the drop down all the emails are getting displayed

**Comment by Moinali5599** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: All users list is displayed on groups page while searching for 1 user](https://trello.com/c/W90eGfVp/30-bug-all-users-list-is-displayed-on-groups-page-while-searching-for-1-user)

**Comment by BhanuMotupalli** [comment]
![Bug 2 resolved](https://github.com/Ajaykumarunt/Best_Team_Ever/assets/126606573/d647d52b-6559-4565-a402-472d759d5da7)
In the code filtered all the emails based on the search made by the user in the search box.
